//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAssignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ExerciseRecord
    {
        public int ID { get; set; }
        [Required]
        [MaxLength(100, ErrorMessage = "Max length is 100")]
        public string ExerciseName { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public System.DateTime ExerciseDate { get; set; }
        [Required]
        [Range(1, 120)]
        public int DurationInMinutes { get; set; }
    }
}
